spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5433/task_tracking'
    username: postgres
    password: password
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: validate
  jackson:
    time-zone: UTC
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
server:
#  error:
#    include-message: always
#    include-exception: true
#    include-binding-errors: always
#    include-stacktrace: never
  port: '8080'
logging:
  level:
    web: debug